In [2]:
import pandas as pd

3.1

In [6]:

s=pd.Series(['banana',42])
print(s)

s=pd.Series(data=['Wes McKinney','Creator of Pandas'],index=['person','who'])
print(s)

0    banana
1        42
dtype: object
person         Wes McKinney
who       Creator of Pandas
dtype: object

In [7]:
scientists = pd.DataFrame({ "Name": ["Rosaline Franklin", "William Gosset"], "Occupation": ["Chemist", "Statistician"], "Born": ["1920-07-25", "1876-06-13"], "Died": ["1958-04-16", "1937-10-16"] ,"Age": [37, 61],})

print(scientists)
print()
scientists=pd.DataFrame({"Occupation": ["Chemist", "Statistician"], "Born": ["1920-07-25", "1876-06-13"], "Died": ["1958-04-16", "1937-10-16"] ,"Age": [37, 61]}, index=["Rosaline Franklin","William Gosset"], columns=["Occupation","Born","Died","Age"])
print(scientists)

                Name    Occupation        Born        Died  Age
0  Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
1     William Gosset  Statistician  1876-06-13  1937-10-16   61

                     Occupation        Born        Died  Age
Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
William Gosset     Statistician  1876-06-13  1937-10-16   61

3.2

In [29]:
scientists=pd.DataFrame({"Occupation": ["Chemist", "Statistician"], "Born": ["1920-07-25", "1876-06-13"], "Died": ["1958-04-16", "1937-10-16"] ,"Age": [37, 61]}, index=["Rosaline Franklin","William Gosset"], columns=["Occupation","Born","Died","Age"])
print(scientists)
print()

first_row=scientists.loc['William Gosset']
print(type(first_row))
print()
print(first_row)
print()

print(first_row.index)
print(first_row.values)
print()

print(first_row.keys())
print()

print(first_row.index[0])
print()

print(first_row.keys()[0])
print()

ages=scientists['Age']
print(ages)
print()

print(ages.mean())
print()

print(ages.min())
print()

print(ages.max())
print()

print(ages.std())
print()

                     Occupation        Born        Died  Age
Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
William Gosset     Statistician  1876-06-13  1937-10-16   61

<class 'pandas.core.series.Series'>

Occupation    Statistician
Born            1876-06-13
Died            1937-10-16
Age                     61
Name: William Gosset, dtype: object

Index(['Occupation', 'Born', 'Died', 'Age'], dtype='object')
['Statistician' '1876-06-13' '1937-10-16' 61]

Index(['Occupation', 'Born', 'Died', 'Age'], dtype='object')

Occupation

Occupation

Rosaline Franklin    37
William Gosset       61
Name: Age, dtype: int64

49.0

37

61

16.97056274847714

In [43]:
scientists = pd.read_csv('/content/drive/MyDrive/KDT AI, 빅데이터 전문가 양성과정/data/scientists.csv')
ages=scientists['Age']
print(ages)
print()

print(ages.describe())
print()

print(ages.mean())
print()

print(ages>ages.mean())
print()

print(ages[ages>ages.mean()])
print()

print(type(ages>ages.mean()))
print()

manual_bool_values=[True,True,False,False, True,True,False,True]
print(ages[manual_bool_values])
print()

print(ages+ages)
print()

print(ages*ages)
print()

print(ages+100)
print()

print(ages*2)
print()


print(ages+pd.Series([1,100]))
print()

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

count     8.000000
mean     59.125000
std      18.325918
min      37.000000
25%      44.000000
50%      58.500000
75%      68.750000
max      90.000000
Name: Age, dtype: float64

59.125

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

<class 'pandas.core.series.Series'>

0    37
1    61
4    56
5    45
7    77
Name: Age, dtype: int64

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

0    1369
1    3721
2    8100
3    4356
4    3136
5    2025
6    1681
7    5929
Name: Age, dtype: int64

0    137
1    161
2    190
3    166
4    156
5    145
6    141
7    177
Name: Age, dtype: int64

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [46]:
import numpy as np

In [47]:
print(ages+np.array([1,100]))

ValueError: operands could not be broadcast together with shapes (8,) (2,)

In [52]:
print(ages)
print()

rev_ages=ages.sort_index(ascending=False)
print(rev_ages)
print()

print(ages*2)
print()

print(ages+rev_ages)

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

7    77
6    41
5    45
4    56
3    66
2    90
1    61
0    37
Name: Age, dtype: int64

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

3.3

In [64]:
print(scientists.index)
print()

print(scientists.columns)
print()

print(scientists.values)
print()

print(scientists.loc[scientists['Age'] > scientists['Age'].mean()])
print()

first_half=scientists[:4]
second_half=scientists[4:]
print(first_half)
print()
print(second_half)
print()

print(scientists*2)
print()

df1=df2=pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]])
df_added=df1.add(df2)
print(df_added)

RangeIndex(start=0, stop=8, step=1)

Index(['Name', 'Born', 'Died', 'Age', 'Occupation'], dtype='object')

[['Rosaline Franklin' '1920-07-25' '1958-04-16' 37 'Chemist']
 ['William Gosset' '1876-06-13' '1937-10-16' 61 'Statistician']
 ['Florence Nightingale' '1820-05-12' '1910-08-13' 90 'Nurse']
 ['Marie Curie' '1867-11-07' '1934-07-04' 66 'Chemist']
 ['Rachel Carson' '1907-05-27' '1964-04-14' 56 'Biologist']
 ['John Snow' '1813-03-15' '1858-06-16' 45 'Physician']
 ['Alan Turing' '1912-06-23' '1954-06-07' 41 'Computer Scientist']
 ['Johann Gauss' '1777-04-30' '1855-02-23' 77 'Mathematician']]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist

            Name        Born        Died  Age          Occupation
4  Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5      John Snow  1813-03-15  1858-06-16   45           Physician
6    Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7   Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

                                       Name                  Born  \
0        Rosaline FranklinRosaline Franklin  1920-07-251920-07-25
1              William GossetWilliam Gosset  1876-06-131876-06-13
2  Florence NightingaleFlorence Nightingale  1820-05-121820-05-12
3                    Marie CurieMarie Curie  1867-11-071867-11-07
4                Rachel CarsonRachel Carson  1907-05-271907-05-27
5                        John SnowJohn Snow  1813-03-151813-03-15
6                    Alan TuringAlan Turing  1912-06-231912-06-23
7                  Johann GaussJohann Gauss  1777-04-301777-04-30

                   Died  Age                            Occupation
0  1958-04-161958-04-16   74                        ChemistChemist
1  1937-10-161937-10-16  122              StatisticianStatistician
2  1910-08-131910-08-13  180                            NurseNurse
3  1934-07-041934-07-04  132                        ChemistChemist
4  1964-04-141964-04-14  112                    BiologistBiologist
5  1858-06-161858-06-16   90                    PhysicianPhysician
6  1954-06-071954-06-07   82  Computer ScientistComputer Scientist
7  1855-02-231855-02-23  154            MathematicianMathematician

    0   1   2
0   2   4   6
1   8  10  12
2  14  16  18

In [63]:
scientists

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician