In [406]:
import pandas as pd

# **지역별 교통사고 분석**

- 시도별 사고가 가장 많이 발생하는 지역 파악

- 위에서 파악한 시도 내에서 어떤 시군구에서 교통사고가 많이 발생했는지 파악

- 위에서 파악한 시군구 안에서 어느 곳에서 왜 교통사고가
  많이 발생했는지 파악

## **시도별 교통사고 데이터를 통해 사고가 가장 많이 발생하는 지역 파악**

In [407]:
file_area='/content/drive/MyDrive/KDT AI, 빅데이터 전문가 양성과정/PANDAS/프로젝트/시도별_교통사고.xlsx'

In [408]:
file_area_df=pd.read_excel(file_area)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [409]:
file_area_df.isna().sum()

시도별(1)    0
월별(1)     0
2018      0
2018.1    0
2018.2    0
2019      0
2019.1    0
2019.2    0
2020      0
2020.1    0
2020.2    0
2021      0
2021.1    0
2021.2    0
2022      0
2022.1    0
2022.2    0
dtype: int64

In [410]:
file_area_df.columns=file_area_df.columns.str[:4]+" "+list(file_area_df.iloc[0])
# 첫 행 통합으로 열 이름이 분리되어 나타나서 열 이름과 0행을 합쳐서 열이름으로 표현하기 위함

In [411]:
file_area_df.columns

Index(['시도별( 시도별(1)', '월별(1 월별(1)', '2018 사고건수 (건)', '2018 사망자수 (명)',
       '2018 부상자수 (명)', '2019 사고건수 (건)', '2019 사망자수 (명)', '2019 부상자수 (명)',
       '2020 사고건수 (건)', '2020 사망자수 (명)', '2020 부상자수 (명)', '2021 사고건수 (건)',
       '2021 사망자수 (명)', '2021 부상자수 (명)', '2022 사고건수 (건)', '2022 사망자수 (명)',
       '2022 부상자수 (명)'],
      dtype='object')

In [412]:
file_area_df.rename(columns={'시도별( 시도별(1)':'시도별(1)','월별(1 월별(1)':'월별(1)'},inplace=True)
# 위의 과정에서 중복되어 저장된 열 이름 재정의

In [413]:
file_area_df.drop(0,inplace=True) # 0행 제거

In [414]:
file_area_df[['2018 사고건수 (건)', '2018 사망자수 (명)',
       '2018 부상자수 (명)', '2019 사고건수 (건)', '2019 사망자수 (명)', '2019 부상자수 (명)',
       '2020 사고건수 (건)', '2020 사망자수 (명)', '2020 부상자수 (명)', '2021 사고건수 (건)',
       '2021 사망자수 (명)', '2021 부상자수 (명)', '2022 사고건수 (건)', '2022 사망자수 (명)',
       '2022 부상자수 (명)']]=file_area_df[['2018 사고건수 (건)', '2018 사망자수 (명)',
       '2018 부상자수 (명)', '2019 사고건수 (건)', '2019 사망자수 (명)', '2019 부상자수 (명)',
       '2020 사고건수 (건)', '2020 사망자수 (명)', '2020 부상자수 (명)', '2021 사고건수 (건)',
       '2021 사망자수 (명)', '2021 부상자수 (명)', '2022 사고건수 (건)', '2022 사망자수 (명)',
       '2022 부상자수 (명)']].astype('int64')

In [415]:
file_area_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 1 to 221
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   시도별(1)         221 non-null    object
 1   월별(1)          221 non-null    object
 2   2018 사고건수 (건)  221 non-null    int64
 3   2018 사망자수 (명)  221 non-null    int64
 4   2018 부상자수 (명)  221 non-null    int64
 5   2019 사고건수 (건)  221 non-null    int64
 6   2019 사망자수 (명)  221 non-null    int64
 7   2019 부상자수 (명)  221 non-null    int64
 8   2020 사고건수 (건)  221 non-null    int64
 9   2020 사망자수 (명)  221 non-null    int64
 10  2020 부상자수 (명)  221 non-null    int64
 11  2021 사고건수 (건)  221 non-null    int64
 12  2021 사망자수 (명)  221 non-null    int64
 13  2021 부상자수 (명)  221 non-null    int64
 14  2022 사고건수 (건)  221 non-null    int64
 15  2022 사망자수 (명)  221 non-null    int64
 16  2022 부상자수 (명)  221 non-null    int64
dtypes: int64(15), object(2)
memory usage: 29.5+ KB

In [416]:
file_area_df=file_area_df.reset_index()

In [417]:
file_area_df=file_area_df.reset_index()
# 멀티 인덱스를 사용하기 위해 두 번 reset_index()

In [418]:
file_area_df.drop('index',axis=1,inplace=True)

In [419]:
file_area_df.rename(columns={'level_0':'index'},inplace=True)

In [420]:
file_area_df.set_index(['index','시도별(1)'],inplace=True)
# 멀티 인덱스 지정

In [421]:
file_area_df

,,월별(1),2018 사고건수 (건),2018 사망자수 (명),2018 부상자수 (명),2019 사고건수 (건),2019 사망자수 (명),2019 부상자수 (명),2020 사고건수 (건),2020 사망자수 (명),2020 부상자수 (명),2021 사고건수 (건),2021 사망자수 (명),2021 부상자수 (명),2022 사고건수 (건),2022 사망자수 (명),2022 부상자수 (명)
index,시도별(1),,,,,,,,,,,,,,,,
0,서울,전체,38795,304,53751,39258,250,53904,35227,219,47513,33913,243,45223,33698,221,45329
1,서울,1월,3192,30,4490,2983,25,4134,2788,18,3944,2717,17,3690,2874,18,3868
2,서울,2월,2973,28,4178,2482,13,3368,2999,20,3980,2505,21,3334,2176,16,2919
3,서울,3월,3072,28,4288,3099,22,4223,2561,21,3385,2789,12,3740,2187,12,2852
4,서울,4월,3219,24,4375,3283,14,4500,2724,17,3724,2952,14,3987,2847,23,3905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,제주,8월,377,6,627,405,5,657,386,4,655,382,7,604,373,4,570
217,제주,9월,338,2,546,352,6,583,352,9,506,335,3,527,326,7,465
218,제주,10월,355,10,532,405,5,626,401,5,663,423,3,641,366,4,554
219,제주,11월,402,13,606,381,7,583,363,12,569,403,3,580,325,4,436
220,제주,12월,339,7,499,370,2,579,291,2,417,361,11,553,296,3,428

In [422]:
file_area_df[file_area_df['월별(1)']=="전체"] # 월별로 나누어진 데이터 보단 전체 데이터 사용

,,월별(1),2018 사고건수 (건),2018 사망자수 (명),2018 부상자수 (명),2019 사고건수 (건),2019 사망자수 (명),2019 부상자수 (명),2020 사고건수 (건),2020 사망자수 (명),2020 부상자수 (명),2021 사고건수 (건),2021 사망자수 (명),2021 부상자수 (명),2022 사고건수 (건),2022 사망자수 (명),2022 부상자수 (명)
index,시도별(1),,,,,,,,,,,,,,,,
0,서울,전체,38795,304,53751,39258,250,53904,35227,219,47513,33913,243,45223,33698,221,45329
13,부산,전체,11937,123,16468,12992,116,17832,11913,100,16347,11339,113,15457,10882,113,14829
26,대구,전체,13199,120,19332,14536,112,21598,12940,112,18974,12133,84,17230,11102,68,15721
39,인천,전체,7632,113,10976,8698,118,12258,8505,91,11950,7912,104,10730,7695,95,10533
52,광주,전체,7459,76,11977,8169,49,13076,7718,63,12293,7543,49,11489,7122,58,10722
65,대전,전체,7554,93,11432,8337,77,12649,7215,66,10636,7027,59,10175,6841,51,9850
78,울산,전체,3992,79,5777,4347,55,6301,3834,51,5444,3801,50,5238,3660,32,5177
91,세종,전체,795,20,1142,922,15,1301,813,7,1076,788,16,1031,932,17,1330
104,경기,전체,53448,678,81174,55463,631,84508,52391,612,77679,53332,537,78225,52968,547,77377
117,강원,전체,7498,197,11922,7554,185,11752,7039,133,10779,6605,145,10221,6425,139,10160
130,충북,전체,9618,224,15687,9538,188,15539,8398,171,13238,7985,160,12135,7644,149,11354
143,충남,전체,8807,354,13283,9404,308,14087,8952,261,13381,8423,265,12197,8164,230,11964
156,전북,전체,6929,246,10452,7615,238,11651,6451,220,9778,6112,193,8906,5681,194,8091
169,전남,전체,9787,330,15680,10877,294,17905,9816,273,15645,8685,255,13522,8335,201,12611
182,경북,전체,13966,409,20919,14648,354,21970,12673,354,18723,12100,334,17690,11037,309,16189
195,경남,전체,11493,333,16454,12830,293,18563,11739,280,16607,11059,257,15414,10611,258,14545
208,제주,전체,4239,82,6611,4412,66,6818,4030,68,6131,4373,52,6725,4039,53,6021

In [423]:
file_area_df_total=file_area_df[file_area_df['월별(1)']=="전체"]
file_area_df_total=file_area_df_total[['2018 사고건수 (건)','2019 사고건수 (건)','2020 사고건수 (건)','2021 사고건수 (건)','2022 사고건수 (건)']]
file_area_df_total

,,2018 사고건수 (건),2019 사고건수 (건),2020 사고건수 (건),2021 사고건수 (건),2022 사고건수 (건)
index,시도별(1),,,,,
0,서울,38795,39258,35227,33913,33698
13,부산,11937,12992,11913,11339,10882
26,대구,13199,14536,12940,12133,11102
39,인천,7632,8698,8505,7912,7695
52,광주,7459,8169,7718,7543,7122
65,대전,7554,8337,7215,7027,6841
78,울산,3992,4347,3834,3801,3660
91,세종,795,922,813,788,932
104,경기,53448,55463,52391,53332,52968
117,강원,7498,7554,7039,6605,6425
130,충북,9618,9538,8398,7985,7644
143,충남,8807,9404,8952,8423,8164
156,전북,6929,7615,6451,6112,5681
169,전남,9787,10877,9816,8685,8335
182,경북,13966,14648,12673,12100,11037
195,경남,11493,12830,11739,11059,10611
208,제주,4239,4412,4030,4373,4039

In [424]:
file_area_df_total.max()

2018 사고건수 (건)    53448
2019 사고건수 (건)    55463
2020 사고건수 (건)    52391
2021 사고건수 (건)    53332
2022 사고건수 (건)    52968
dtype: int64

In [425]:
file_area_df_total.reset_index(inplace=True) # 멀티인덱스 해제

In [426]:
file_area_df_total.set_index('시도별(1)',inplace=True) # 시도별을 새 인덱스로 지정

In [427]:
file_area_df_total.drop('index',axis=1,inplace=True)

In [428]:
file_area_df_total

,2018 사고건수 (건),2019 사고건수 (건),2020 사고건수 (건),2021 사고건수 (건),2022 사고건수 (건)
시도별(1),,,,,
서울,38795,39258,35227,33913,33698
부산,11937,12992,11913,11339,10882
대구,13199,14536,12940,12133,11102
인천,7632,8698,8505,7912,7695
광주,7459,8169,7718,7543,7122
대전,7554,8337,7215,7027,6841
울산,3992,4347,3834,3801,3660
세종,795,922,813,788,932
경기,53448,55463,52391,53332,52968
강원,7498,7554,7039,6605,6425
충북,9618,9538,8398,7985,7644
충남,8807,9404,8952,8423,8164
전북,6929,7615,6451,6112,5681
전남,9787,10877,9816,8685,8335
경북,13966,14648,12673,12100,11037
경남,11493,12830,11739,11059,10611
제주,4239,4412,4030,4373,4039

In [429]:
file_area_df_total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 서울 to 제주
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   2018 사고건수 (건)  17 non-null     int64
 1   2019 사고건수 (건)  17 non-null     int64
 2   2020 사고건수 (건)  17 non-null     int64
 3   2021 사고건수 (건)  17 non-null     int64
 4   2022 사고건수 (건)  17 non-null     int64
dtypes: int64(5)
memory usage: 816.0+ bytes

In [430]:
file_area_df_total.max().values

array([53448, 55463, 52391, 53332, 52968])

In [431]:
file_area_df_total.idxmax(axis=0) # 최대값을 가지는 인덱스 반환

2018 사고건수 (건)    경기
2019 사고건수 (건)    경기
2020 사고건수 (건)    경기
2021 사고건수 (건)    경기
2022 사고건수 (건)    경기
dtype: object

조사한 모든년도 2018, 2019, 2020, 2021, 2022 에서 경기의 교통사고 발생 수가 가장 많음

## **시군구별 데이터를 통해 경기도 내부 어느 곳에서 교통사고가 많이 발생했는지 파악**

In [432]:
file_area_c='/content/drive/MyDrive/KDT AI, 빅데이터 전문가 양성과정/PANDAS/프로젝트/시도_시군구별 교통사고.xls'

file_area_c_df=pd.read_excel(file_area_c, skiprows=2) # 첫 행 2개에 데이터에 관한 정보가 있으므로 빼고 read

In [433]:
file_area_c_df.columns=file_area_c_df.columns.str[:4]+" "+list(file_area_c_df.iloc[0])
# 위에서와 동일하게 열 이름과 0행을 합쳐서 열로 표현하기 위함

In [434]:
file_area_c_df.columns

Index(['시도 시도', '시군구 시군구', '2018 사고[건]', '2018 사망[명]', '2018 부상[명]',
       '2019 사고[건]', '2019 사망[명]', '2019 부상[명]', '2020 사고[건]', '2020 사망[명]',
       '2020 부상[명]', '2021 사고[건]', '2021 사망[명]', '2021 부상[명]', '2022 사고[건]',
       '2022 사망[명]', '2022 부상[명]'],
      dtype='object')

In [435]:
file_area_c_df.rename(columns={'시도 시도':'시도','시군구 시군구':'시군구'},inplace=True)
# 위에서와 동일하게 중복되어 저장된 열이름 재지정
file_area_c_df.drop(0,inplace=True)

In [436]:
file_area_c_df.drop(230,inplace=True)

In [437]:
file_area_c_df

,시도,시군구,2018 사고[건],2018 사망[명],2018 부상[명],2019 사고[건],2019 사망[명],2019 부상[명],2020 사고[건],2020 사망[명],2020 부상[명],2021 사고[건],2021 사망[명],2021 부상[명],2022 사고[건],2022 사망[명],2022 부상[명]
1,서울,종로구,1134,6,1546,1133,6,1559,903,5,1224,778,6,1050,974,3,1351
2,서울,중구,1128,9,1506,1184,5,1615,955,6,1248,854,3,1156,943,2,1212
3,서울,용산구,1330,14,1852,1187,10,1614,890,12,1178,1014,5,1369,1014,11,1330
4,서울,성동구,1143,9,1561,1091,13,1439,1119,9,1481,1057,8,1362,948,8,1222
5,서울,동대문구,1699,14,2160,1565,15,1988,1448,10,1845,1390,17,1656,1534,12,1843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,경남,거창군,242,8,324,250,15,320,253,18,317,274,9,359,228,10,305
226,경남,합천군,168,9,221,184,10,242,216,12,295,152,4,208,151,8,229
227,경남,창원시(통합),2916,64,4053,3245,62,4524,2978,59,4149,2556,52,3511,2649,61,3510
228,제주,제주시,3003,42,4531,3139,40,4766,2879,44,4263,3062,34,4625,2790,39,4122
229,제주,서귀포시,1236,40,2080,1273,26,2052,1151,24,1868,1311,18,2100,1249,14,1899

In [438]:
file_area_c_df_gg=file_area_c_df[file_area_c_df['시도']=="경기"].copy() # 경기도 데이터만 추출
file_area_c_df_gg

,시도,시군구,2018 사고[건],2018 사망[명],2018 부상[명],2019 사고[건],2019 사망[명],2019 부상[명],2020 사고[건],2020 사망[명],2020 부상[명],2021 사고[건],2021 사망[명],2021 부상[명],2022 사고[건],2022 사망[명],2022 부상[명]
76,경기,수원시,4997,39,7148,4920,31,7044,4480,29,6459,4615,25,6667,4705,25,6569
77,경기,성남시,3834,37,5635,3801,39,5745,3640,31,5204,3398,27,4751,3599,27,5063
78,경기,의정부시,1682,19,2401,1704,17,2462,1695,13,2479,1690,18,2354,1683,13,2304
79,경기,안양시,1618,14,2356,1616,20,2366,1337,9,1958,1182,13,1690,1134,15,1616
80,경기,부천시,3236,22,4550,3667,23,5108,3364,23,4716,3436,19,4655,3457,18,4695
81,경기,안산시,3878,42,5909,3965,27,5942,3931,35,5753,3821,20,5525,3685,22,5388
82,경기,평택시,3388,51,5465,3527,51,5730,3190,41,4819,3321,36,5051,3508,56,5246
83,경기,광명시,1076,12,1520,1068,9,1504,964,4,1377,992,10,1347,950,10,1300
84,경기,구리시,668,11,966,751,6,1103,758,6,1097,737,9,1074,716,2,1102
85,경기,양주시,1094,19,1629,1118,19,1685,1027,14,1520,998,6,1448,1123,14,1595
86,경기,여주시,513,14,814,592,17,983,507,16,859,538,14,929,558,15,940
87,경기,화성시,2716,59,4257,3008,33,4782,2959,45,4375,3075,37,4548,3230,43,4768
88,경기,시흥시,2434,29,3652,2480,30,3880,2293,26,3497,2385,32,3615,2372,22,3493
89,경기,파주시,1693,22,2585,1658,21,2408,1475,34,1997,1708,28,2428,1673,27,2372
90,경기,고양시,3950,38,5889,3916,39,5794,3586,37,5112,3532,39,5001,3588,37,5079
91,경기,광주시,1691,19,2622,1867,20,2871,1930,27,2924,2265,17,3481,2178,12,3251
92,경기,연천군,189,6,313,196,11,308,203,5,316,199,6,321,178,8,283
93,경기,포천시,832,16,1413,887,15,1475,829,26,1347,914,15,1410,826,16,1336
94,경기,가평군,380,11,682,396,8,678,364,5,595,367,10,651,400,3,675
95,경기,양평군,532,15,826,591,13,955,553,9,920,504,20,812,490,15,751
96,경기,이천시,1016,19,1626,1102,33,1687,1106,25,1708,1192,14,1860,1050,20,1607
97,경기,용인시,3205,37,5116,3485,34,5698,3262,35,5066,3603,31,5401,3562,32,5477
98,경기,안성시,1026,19,1740,1014,16,1734,1075,13,1779,1072,24,1717,896,17,1499
99,경기,김포시,1682,24,2664,1792,24,2787,1687,29,2632,1775,18,2669,1933,11,2926
100,경기,동두천시,406,11,576,417,6,565,329,4,456,351,2,477,273,5,376
101,경기,과천시,239,1,385,237,1,380,187,6,290,168,1,256,208,4,354
102,경기,군포시,659,7,954,650,3,1024,709,9,1043,622,9,904,593,9,867
103,경기,남양주시,2431,41,3903,2411,31,3843,2255,32,3419,2136,18,3257,1970,24,2927
104,경기,오산시,962,10,1409,1057,7,1582,1090,6,1559,1108,7,1571,997,10,1418
105,경기,의왕시,444,5,726,488,10,780,414,5,615,433,3,624,300,10,471
106,경기,하남시,977,9,1443,1082,17,1605,1192,13,1788,1195,9,1731,1133,5,1629

In [439]:
file_area_c_df_gg[['2018 사고[건]', '2018 사망[명]', '2018 부상[명]', '2019 사고[건]',
       '2019 사망[명]', '2019 부상[명]', '2020 사고[건]', '2020 사망[명]', '2020 부상[명]',
       '2021 사고[건]', '2021 사망[명]', '2021 부상[명]', '2022 사고[건]', '2022 사망[명]',
       '2022 부상[명]']]=file_area_c_df_gg[['2018 사고[건]', '2018 사망[명]', '2018 부상[명]', '2019 사고[건]',
       '2019 사망[명]', '2019 부상[명]', '2020 사고[건]', '2020 사망[명]', '2020 부상[명]',
       '2021 사고[건]', '2021 사망[명]', '2021 부상[명]', '2022 사고[건]', '2022 사망[명]',
       '2022 부상[명]']].astype('int64')

In [440]:
file_area_c_df_gg_1=file_area_c_df_gg[['시군구','2018 사고[건]','2019 사고[건]','2020 사고[건]','2021 사고[건]','2022 사고[건]']].set_index('시군구')
file_area_c_df_gg_1

      2018 사고[건]  2019 사고[건]  2020 사고[건]  2021 사고[건]  2022 사고[건]
시군구
수원시         4997        4920        4480        4615        4705
성남시         3834        3801        3640        3398        3599
의정부시        1682        1704        1695        1690        1683
안양시         1618        1616        1337        1182        1134
부천시         3236        3667        3364        3436        3457
안산시         3878        3965        3931        3821        3685
평택시         3388        3527        3190        3321        3508
광명시         1076        1068         964         992         950
구리시          668         751         758         737         716
양주시         1094        1118        1027         998        1123
여주시          513         592         507         538         558
화성시         2716        3008        2959        3075        3230
시흥시         2434        2480        2293        2385        2372
파주시         1693        1658        1475        1708        1673
고양시         3950        3916        3586        3532        3588
광주시         1691        1867        1930        2265        2178
연천군          189         196         203         199         178
포천시          832         887         829         914         826
가평군          380         396         364         367         400
양평군          532         591         553         504         490
이천시         1016        1102        1106        1192        1050
용인시         3205        3485        3262        3603        3562
안성시         1026        1014        1075        1072         896
김포시         1682        1792        1687        1775        1933
동두천시         406         417         329         351         273
과천시          239         237         187         168         208
군포시          659         650         709         622         593
남양주시        2431        2411        2255        2136        1970
오산시          962        1057        1090        1108         997
의왕시          444         488         414         433         300
하남시          977        1082        1192        1195        1133

In [441]:
file_area_c_df_gg_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 수원시 to 하남시
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   2018 사고[건]  31 non-null     int64
 1   2019 사고[건]  31 non-null     int64
 2   2020 사고[건]  31 non-null     int64
 3   2021 사고[건]  31 non-null     int64
 4   2022 사고[건]  31 non-null     int64
dtypes: int64(5)
memory usage: 1.5+ KB

In [442]:
file_area_c_df_gg_1.max()

2018 사고[건]    4997
2019 사고[건]    4920
2020 사고[건]    4480
2021 사고[건]    4615
2022 사고[건]    4705
dtype: int64

In [443]:
file_area_c_df_gg_1.idxmax(axis=0) # 최대값의 인덱스를 반환

2018 사고[건]    수원시
2019 사고[건]    수원시
2020 사고[건]    수원시
2021 사고[건]    수원시
2022 사고[건]    수원시
dtype: object

모든년도에서 경기 중 수원시의 교통사고 발생 수가 가장 많음

### **이전 데이터에서 경기 다음으로 서울이 높았기 때문에 서울 데이터 추출하여 수원시와 비교**

In [444]:
file_area_c_df_se=file_area_c_df[file_area_c_df['시도']=="서울"].copy() # 서울 데이터만 추출

In [445]:
file_area_c_df_se[['2018 사고[건]', '2018 사망[명]', '2018 부상[명]', '2019 사고[건]',
       '2019 사망[명]', '2019 부상[명]', '2020 사고[건]', '2020 사망[명]', '2020 부상[명]',
       '2021 사고[건]', '2021 사망[명]', '2021 부상[명]', '2022 사고[건]', '2022 사망[명]',
       '2022 부상[명]']]=file_area_c_df_se[['2018 사고[건]', '2018 사망[명]', '2018 부상[명]', '2019 사고[건]',
       '2019 사망[명]', '2019 부상[명]', '2020 사고[건]', '2020 사망[명]', '2020 부상[명]',
       '2021 사고[건]', '2021 사망[명]', '2021 부상[명]', '2022 사고[건]', '2022 사망[명]',
       '2022 부상[명]']].astype('int64')

In [446]:
file_area_c_df_se_1=file_area_c_df_se[['시군구','2018 사고[건]','2019 사고[건]','2020 사고[건]','2021 사고[건]','2022 사고[건]']].set_index('시군구')
file_area_c_df_se_1

      2018 사고[건]  2019 사고[건]  2020 사고[건]  2021 사고[건]  2022 사고[건]
시군구
종로구         1134        1133         903         778         974
중구          1128        1184         955         854         943
용산구         1330        1187         890        1014        1014
성동구         1143        1091        1119        1057         948
동대문구        1699        1565        1448        1390        1534
성북구         1427        1509        1275        1285        1288
도봉구          824         852         741         591         522
은평구         1134        1119         953         867         918
서대문구        1033        1113         928         930         974
마포구         1671        1494        1272        1102        1065
강서구         1502        1829        1575        1501        1606
구로구         1532        1529        1325        1350        1274
영등포구        2493        2439        2208        2178        1998
동작구         1412        1406        1307        1148        1217
관악구         1300        1363        1444        1419        1172
강남구         3459        3722        3752        3820        3709
강동구         1418        1414        1268        1047        1151
송파구         2860        2892        2595        2607        2581
서초구         2478        2418        2250        2118        2264
양천구         1428        1506        1344        1305        1165
중랑구         1565        1620        1447        1373        1401
노원구         1569        1703        1462        1413        1384
광진구         1108         973         869         922         708
강북구         1216        1277        1087        1017        1044
금천구          932         920         810         827         844

In [447]:
file_area_c_df_se_1.max()

2018 사고[건]    3459
2019 사고[건]    3722
2020 사고[건]    3752
2021 사고[건]    3820
2022 사고[건]    3709
dtype: int64

In [448]:
file_area_c_df_se_1.idxmax(axis=0) # 최대값을 가지는 인덱스 반환

2018 사고[건]    강남구
2019 사고[건]    강남구
2020 사고[건]    강남구
2021 사고[건]    강남구
2022 사고[건]    강남구
dtype: object

In [449]:
file_area_c_df_se_1.loc['강남구'].describe()

count       5.00000
mean     3692.40000
std       137.35101
min      3459.00000
25%      3709.00000
50%      3722.00000
75%      3752.00000
max      3820.00000
Name: 강남구, dtype: float64

In [450]:
file_area_c_df_gg_1.loc['수원시'].describe()

count       5.000000
mean     4743.400000
std       213.799673
min      4480.000000
25%      4615.000000
50%      4705.000000
75%      4920.000000
max      4997.000000
Name: 수원시, dtype: float64

참고) 서울에서 강남구의 교통사고 사고 수가 경기의 수원시보다 낮으므로 경기도 수원시를 주제로 분석 실시

- 강남구의 최대값이 수원시의 최소값보다 훨씬 작음
- 구와 시를 비교하는 것은 올바르지 않지만 서울 강남구에서는 교통사고 발생 수가 많을 것으로 예상하였지만 수원시는 예상하지 못한 결과이므로 수원시 분석을 결정

In [451]:
file_area_c_df_gg.loc[76] # 수원시 데이터 추출

시도              경기
시군구            수원시
2018 사고[건]    4997
2018 사망[명]      39
2018 부상[명]    7148
2019 사고[건]    4920
2019 사망[명]      31
2019 부상[명]    7044
2020 사고[건]    4480
2020 사망[명]      29
2020 부상[명]    6459
2021 사고[건]    4615
2021 사망[명]      25
2021 부상[명]    6667
2022 사고[건]    4705
2022 사망[명]      25
2022 부상[명]    6569
Name: 76, dtype: object

사망자, 부상자가 주로 어디에서 발생하는지 알아내기 위해 분석 실시

## **사망 교통사고 현황 데이터를 통해 수원시 내부 어느 곳에서 교통사고 많이 발생했는지 파악**

In [452]:
file_area_suwon='/content/drive/MyDrive/KDT AI, 빅데이터 전문가 양성과정/PANDAS/프로젝트/사망교통사고현황.xls'

file_area_suwon_df=pd.read_excel(file_area_suwon)

In [453]:
file_area_suwon_df=file_area_suwon_df[file_area_suwon_df['시군명']=="수원시"]

In [454]:
file_area_suwon_df=file_area_suwon_df[['시군명','발생년도','발생일자','WGS84위도','WGS84경도']]

In [455]:
file_area_suwon_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 448 entries, 13 to 7763
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   시군명      448 non-null    object
 1   발생년도     448 non-null    int64
 2   발생일자     448 non-null    object
 3   WGS84위도  448 non-null    float64
 4   WGS84경도  448 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 21.0+ KB

In [456]:
file_area_suwon_df.isna().sum()

시군명        0
발생년도       0
발생일자       0
WGS84위도    0
WGS84경도    0
dtype: int64

In [457]:
file_area_suwon_df=file_area_suwon_df[(file_area_suwon_df['발생년도']<=2022) & (file_area_suwon_df['발생년도']>=2018)].copy()
# 조사하고자 하는 년도인 2018~2022 사이의 데이터만 추출

In [458]:
file_area_suwon_df.reset_index(inplace=True)
# 추출한 데이터의 인덱스가 연속적이지 않아서 reset_index()

In [459]:
file_area_suwon_df
file_area_suwon_df.drop('index',axis=1)

     시군명  발생년도            발생일자    WGS84위도     WGS84경도
0    수원시  2022  2022-12-22 14시  37.265536  127.015079
1    수원시  2022  2022-11-12 23시  37.291458  127.010028
2    수원시  2022  2022-10-29 00시  37.262897  127.049798
3    수원시  2022  2022-10-06 11시  37.304095  126.992862
4    수원시  2022  2022-09-22 10시  37.320332  126.983193
..   ...   ...             ...        ...         ...
143  수원시  2018  2018-03-23 12시  37.292173  127.015122
144  수원시  2018  2018-03-22 02시  37.258096  127.077455
145  수원시  2018  2018-02-28 19시  37.270622  127.017810
146  수원시  2018  2018-02-04 20시  37.252166  127.014387
147  수원시  2018  2018-01-24 22시  37.284163  126.983948

[148 rows x 5 columns]

In [460]:
file_area_suwon_df['발생위치']=['팔달구', '장안구', '영통구', '장안구', '장안구', '권선구', '장안구', '권선구',
                            '장안구', '권선구', '팔달구', '권선구', '장안구', '영통구', '팔달구', '장안구', '장안구',
                            '팔달구', '팔달구', '권선구', '권선구', '팔달구', '팔달구', '장안구', '팔달구', '권선구',
                            '권선구', '권선구', '권선구', '권선구', '팔달구', '장안구', '권선구', '장안구', '영통구',
                            '권선구', '권선구', '권선구', '권선구', '영통구', '권선구', '팔달구', '영통구', '팔달구',
                            '팔달구', '권선구', '권선구', '팔달구', '권선구', '장안구', '권선구', '팔달구', '권선구',
                            '장안구', '영통구', '팔달구', '팔달구', '영통구', '권선구', '장안구', '장안구', '장안구',
                            '장안구', '장안구', '권선구', '권선구', '권선구', '영통구', '팔달구', '장안구', '영통구',
                            '팔달구', '권선구', '영통구', '장안구', '영통구', '영통구', '권선구', '권선구', '팔달구',
                            '용인시 기흥구', '영통구', '권선구', '팔달구', '권선구', '권선구', '권선구', '권선구',
                            '권선구', '팔달구', '영통구', '팔달구', '팔달구', '용인시 기흥구', '권선구', '팔달구',
                            '팔달구', '권선구', '권선구', '권선구', '영통구', '권선구', '권선구', '영통구', '권선구',
                            '영통구', '영통구', '장안구', '장안구', '팔달구', '장안구', '팔달구', '장안구', '장안구',
                            '팔달구', '권선구', '권선구', '장안구', '팔달구', '영통구', '영통구', '권선구', '팔달구',
                            '팔달구', '권선구', '영통구', '권선구', '영통구', '팔달구', '팔달구', '장안구', '장안구',
                            '권선구', '권선구', '장안구', '장안구', '장안구', '권선구', '팔달구', '팔달구', '장안구',
                            '장안구', '권선구', '장안구', '영통구', '팔달구', '권선구', '팔달구']

# 데이터의 위도, 경도를 통 교통사고 발생 지역의 구를 조사

In [461]:
file_area_suwon_df

     index  시군명  발생년도            발생일자    WGS84위도     WGS84경도 발생위치
0       13  수원시  2022  2022-12-22 14시  37.265536  127.015079  팔달구
1       70  수원시  2022  2022-11-12 23시  37.291458  127.010028  장안구
2       91  수원시  2022  2022-10-29 00시  37.262897  127.049798  영통구
3      125  수원시  2022  2022-10-06 11시  37.304095  126.992862  장안구
4      140  수원시  2022  2022-09-22 10시  37.320332  126.983193  장안구
..     ...  ...   ...             ...        ...         ...  ...
143   2517  수원시  2018  2018-03-23 12시  37.292173  127.015122  장안구
144   2521  수원시  2018  2018-03-22 02시  37.258096  127.077455  영통구
145   2545  수원시  2018  2018-02-28 19시  37.270622  127.017810  팔달구
146   2574  수원시  2018  2018-02-04 20시  37.252166  127.014387  권선구
147   2595  수원시  2018  2018-01-24 22시  37.284163  126.983948  팔달구

[148 rows x 7 columns]

In [462]:
file_area_suwon_df['발생위치'].value_counts()

발생위치
권선구        52
팔달구        37
장안구        34
영통구        23
용인시 기흥구     2
Name: count, dtype: int64

In [463]:
file_area_suwon_df['발생위치'].mode()

0    권선구
Name: 발생위치, dtype: object

수원시 권선구에서 대부분 교통사고 발생한다는 사실을 알 수 있다

In [464]:
file_area_suwon_df['발생위치'].value_counts()

발생위치
권선구        52
팔달구        37
장안구        34
영통구        23
용인시 기흥구     2
Name: count, dtype: int64

In [465]:
file_area_suwon_df[file_area_suwon_df['발생위치']=="권선구"] # 권선구 데이터만 추출

     index  시군명  발생년도            발생일자    WGS84위도     WGS84경도 발생위치
5      145  수원시  2022  2022-09-20 02시  37.273189  126.962795  권선구
7      159  수원시  2022  2022-09-09 23시  37.249947  127.018517  권선구
9      203  수원시  2022  2022-08-01 00시  37.255288  127.008661  권선구
11     240  수원시  2022  2022-07-08 14시  37.275557  126.980318  권선구
19     345  수원시  2022  2022-04-17 19시  37.263486  127.009577  권선구
20     371  수원시  2022  2022-03-21 10시  37.252607  127.005600  권선구
25     451  수원시  2021  2021-12-27 14시  37.256714  126.994037  권선구
26     466  수원시  2021  2021-12-13 07시  37.252030  127.014320  권선구
27     471  수원시  2021  2021-12-11 02시  37.250497  127.041121  권선구
28     483  수원시  2021  2021-12-07 16시  37.249750  127.018743  권선구
29     487  수원시  2021  2021-12-06 12시  37.237704  126.981706  권선구
32     514  수원시  2021  2021-11-17 14시  37.273611  126.966345  권선구
35     598  수원시  2021  2021-10-06 04시  37.251310  127.041601  권선구
36     619  수원시  2021  2021-09-25 05시  37.246779  126.967065  권선구
37     670  수원시  2021  2021-08-14 02시  37.271263  126.992112  권선구
38     725  수원시  2021  2021-07-09 18시  37.249561  126.984635  권선구
40     793  수원시  2021  2021-05-14 20시  37.251812  127.011626  권선구
45     884  수원시  2021  2021-03-12 21시  37.243215  126.958205  권선구
46     907  수원시  2021  2021-02-23 21시  37.293083  126.953143  권선구
48     971  수원시  2021  2021-01-01 21시  37.236327  126.976011  권선구
50    1039  수원시  2020  2020-10-31 02시  37.277161  126.962113  권선구
52    1076  수원시  2020  2020-10-07 15시  37.275911  126.976831  권선구
58    1208  수원시  2020  2020-07-11 14시  37.243316  127.030578  권선구
64    1292  수원시  2020  2020-05-10 22시  37.258175  126.973491  권선구
65    1317  수원시  2020  2020-04-23 06시  37.262468  127.014185  권선구
66    1355  수원시  2020  2020-03-26 09시  37.264922  127.008260  권선구
72    1416  수원시  2020  2020-02-09 21시  37.263579  127.008178  권선구
77    1490  수원시  2020  2020-01-02 06시  37.261472  126.957228  권선구
78    1494  수원시  2019  2019-12-30 07시  37.260365  127.022465  권선구
82    1537  수원시  2019  2019-12-05 12시  37.287252  126.943664  권선구
84    1575  수원시  2019  2019-11-19 20시  37.247723  127.027889  권선구
85    1576  수원시  2019  2019-11-17 06시  37.280807  126.969013  권선구
86    1581  수원시  2019  2019-11-15 08시  37.231245  127.021285  권선구
87    1614  수원시  2019  2019-10-28 13시  37.253514  127.011221  권선구
88    1621  수원시  2019  2019-10-25 00시  37.275846  126.958332  권선구
94    1727  수원시  2019  2019-08-20 11시  37.249124  127.026674  권선구
97    1863  수원시  2019  2019-05-13 20시  37.275143  126.956465  권선구
98    1884  수원시  2019  2019-05-03 03시  37.283662  126.980804  권선구
99    1895  수원시  2019  2019-04-25 05시  37.273542  126.965207  권선구
101   1929  수원시  2019  2019-04-05 23시  37.263660  127.008133  권선구
102   1931  수원시  2019  2019-04-05 13시  37.248029  126.970405  권선구
104   1968  수원시  2019  2019-03-13 06시  37.251075  126.981285  권선구
115   2178  수원시  2018  2018-11-17 05시  37.251442  127.011550  권선구
116   2187  수원시  2018  2018-11-11 03시  37.242851  126.979619  권선구
121   2232  수원시  2018  2018-10-08 03시  37.263741  127.023650  권선구
124   2251  수원시  2018  2018-09-21 21시  37.254789  127.027778  권선구
126   2259  수원시  2018  2018-09-18 14시  37.250917  127.017563  권선구
132   2350  수원시  2018  2018-07-26 01시  37.259671  126.973436  권선구
133   2359  수원시  2018  2018-07-15 07시  37.267090  126.971557  권선구
137   2419  수원시  2018  2018-06-02 16시  37.276221  126.979671  권선구
142   2488  수원시  2018  2018-04-10 15시  37.258324  126.997454  권선구
146   2574  수원시  2018  2018-02-04 20시  37.252166  127.014387  권선구

In [466]:
file_area_suwon_df_k=file_area_suwon_df[file_area_suwon_df['발생위치']=="권선구"]

file_area_suwon_df_k[['WGS84위도','WGS84경도']].mean()

WGS84위도     37.259595
WGS84경도    126.993394
dtype: float64

권선구의 위도와 경도를 평균한 장소는 중고차 매매 회사인 수원 sk v1 motors
- 이후 시각화를 통해 기존 위도 경도 데이터와 어떠한 연관성이 있는지 쉽게 파악하면 좋을 거 같다.
- 위의 분석을 통해 sk v1 motors가 교통사고가 많이 나타나는 장소라고 하는 것이 유의미한 결과라고 할 수 없다.

### **수원시 권선구는 왜 교통사고가 많이 발생할까 ?**

수원시 권선구는 수원의 중심지로서 관광명소로 많은 장소들이 존재한다.
- 경기상상캠퍼스 : 문화예술과 자연이 어우러진 복합문화공간

- 마중공원 : 생태 연못, 초화원, 어린이 놀이터, 물놀이장, 반려견 쉼터, 저류지, 잔디광장 등의 시설 보유

- 올림픽공원 : 1987년 88서울올림픽 개최를 기념하기 위하여 조성

- 정수농장 : 딸기/토마토/감자 농가 체험

- 도나스데이 본점 : 수원 오목천동 도넛 맛집으로 유명한 도나스데이 본점

- 무궁화전박물관 :  한지를 이용하여 무궁화와 우리들의 들꽃을 실물과 같이 재현한 곳

- 포시즌힐링팜 : 체험형 치유농장

- 수달앤쥬 : 흔히 보기 힘든 동물들이 있는 실내 동물원


등이 있다.

=> 수원의 중심지이자 관광명소로 유명한 곳이 많아서 교통사고 발생 수가 가장 높다고 할 수 있다.



---

2018, 2019, 2020, 2021, 2022 년도의 교통사고 발생 수가

경기에서 가장 많고 경기도 내부에서는 수원시가 가장 많이 발생하였다는 사실을 알 수 있다.


또한 수원시 내에서는 수원의 중심지이자 관광명소로 유명한 곳이 많은 권선구에서

대부분의 교통사고가 발생하고 많은 사상자와 부상자가 발생한다는 것이 밝혀졌다.