In [ ]:
import pandas as pd

In [ ]:
file_name = '/content/drive/MyDrive/KDT AI, 빅데이터 전문가 양성과정/평일과제/work_07_16_이송은/titanic.csv'

file=pd.read_csv(file_name)
file

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
file_1=file[file['alive']=='yes']

In [ ]:
file_1['sex'].value_counts()

sex
female    233
male      109
Name: count, dtype: int64

남성의 생존률이 여성의 생존률보다 낮음



---

In [ ]:
file_s=file[['survived','sex','age','adult_male','deck','embark_town','alive']]
file_s

     survived     sex   age  adult_male deck  embark_town alive
0           0    male  22.0        True  NaN  Southampton    no
1           1  female  38.0       False    C    Cherbourg   yes
2           1  female  26.0       False  NaN  Southampton   yes
3           1  female  35.0       False    C  Southampton   yes
4           0    male  35.0        True  NaN  Southampton    no
..        ...     ...   ...         ...  ...          ...   ...
886         0    male  27.0        True  NaN  Southampton    no
887         1  female  19.0       False    B  Southampton   yes
888         0  female   NaN       False  NaN  Southampton    no
889         1    male  26.0        True    C    Cherbourg   yes
890         0    male  32.0        True  NaN   Queenstown    no

[891 rows x 7 columns]

In [ ]:
file_s_c=file_s[(file_s['alive']=='yes') & (file_s['sex']=='male' )].copy()
file_s_c

     survived   sex   age  adult_male deck  embark_town alive
17          1  male   NaN        True  NaN  Southampton   yes
21          1  male  34.0        True    D  Southampton   yes
23          1  male  28.0        True    A  Southampton   yes
36          1  male   NaN        True  NaN    Cherbourg   yes
55          1  male   NaN        True    C  Southampton   yes
..        ...   ...   ...         ...  ...          ...   ...
838         1  male  32.0        True  NaN  Southampton   yes
839         1  male   NaN        True    C    Cherbourg   yes
857         1  male  51.0        True    E  Southampton   yes
869         1  male   4.0       False  NaN  Southampton   yes
889         1  male  26.0        True    C    Cherbourg   yes

[109 rows x 7 columns]

In [ ]:
file_s_c.isna().sum()

survived        0
sex             0
age            16
adult_male      0
deck           64
embark_town     0
alive           0
dtype: int64

In [ ]:
file_s_c.fillna({'deck':'unknown'},inplace=True)

In [ ]:
file_s_c

     survived   sex   age  adult_male     deck  embark_town alive
17          1  male   NaN        True  unknown  Southampton   yes
21          1  male  34.0        True        D  Southampton   yes
23          1  male  28.0        True        A  Southampton   yes
36          1  male   NaN        True  unknown    Cherbourg   yes
55          1  male   NaN        True        C  Southampton   yes
..        ...   ...   ...         ...      ...          ...   ...
838         1  male  32.0        True  unknown  Southampton   yes
839         1  male   NaN        True        C    Cherbourg   yes
857         1  male  51.0        True        E  Southampton   yes
869         1  male   4.0       False  unknown  Southampton   yes
889         1  male  26.0        True        C    Cherbourg   yes

[109 rows x 7 columns]

In [ ]:
file_s_c.isna().sum()

survived        0
sex             0
age            16
adult_male      0
deck            0
embark_town     0
alive           0
dtype: int64

특정 컬럼인 'age'만 NaN 여부 검사 진행

In [ ]:
file_s_c=file_s_c.dropna(subset=['age']).copy()

In [ ]:
file_s_c.isna().sum()

survived       0
sex            0
age            0
adult_male     0
deck           0
embark_town    0
alive          0
dtype: int64

In [ ]:
file_s_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 21 to 889
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     93 non-null     int64
 1   sex          93 non-null     object
 2   age          93 non-null     float64
 3   adult_male   93 non-null     bool
 4   deck         93 non-null     object
 5   embark_town  93 non-null     object
 6   alive        93 non-null     object
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 5.2+ KB

In [ ]:
file_s_c['age']//10

21     3.0
23     2.0
74     3.0
78     0.0
81     2.0
      ...
831    0.0
838    3.0
857    5.0
869    0.0
889    2.0
Name: age, Length: 93, dtype: float64

In [ ]:
file_s_c['age_group']=file_s_c['age']//10

In [ ]:
file_s_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 21 to 889
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     93 non-null     int64
 1   sex          93 non-null     object
 2   age          93 non-null     float64
 3   adult_male   93 non-null     bool
 4   deck         93 non-null     object
 5   embark_town  93 non-null     object
 6   alive        93 non-null     object
 7   age_group    93 non-null     float64
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 5.9+ KB

In [ ]:
file_s_c

     survived   sex    age  adult_male     deck  embark_town alive  age_group
21          1  male  34.00        True        D  Southampton   yes        3.0
23          1  male  28.00        True        A  Southampton   yes        2.0
74          1  male  32.00        True  unknown  Southampton   yes        3.0
78          1  male   0.83       False  unknown  Southampton   yes        0.0
81          1  male  29.00        True  unknown  Southampton   yes        2.0
..        ...   ...    ...         ...      ...          ...   ...        ...
831         1  male   0.83       False  unknown  Southampton   yes        0.0
838         1  male  32.00        True  unknown  Southampton   yes        3.0
857         1  male  51.00        True        E  Southampton   yes        5.0
869         1  male   4.00       False  unknown  Southampton   yes        0.0
889         1  male  26.00        True        C    Cherbourg   yes        2.0

[93 rows x 8 columns]

In [ ]:
file_s_c.iloc[:, -1] = file_s_c.iloc[:, -1].astype(int).astype(str)+"0대"
file_s_c

     survived   sex    age  adult_male     deck  embark_town alive age_group
21          1  male  34.00        True        D  Southampton   yes       30대
23          1  male  28.00        True        A  Southampton   yes       20대
74          1  male  32.00        True  unknown  Southampton   yes       30대
78          1  male   0.83       False  unknown  Southampton   yes       00대
81          1  male  29.00        True  unknown  Southampton   yes       20대
..        ...   ...    ...         ...      ...          ...   ...       ...
831         1  male   0.83       False  unknown  Southampton   yes       00대
838         1  male  32.00        True  unknown  Southampton   yes       30대
857         1  male  51.00        True        E  Southampton   yes       50대
869         1  male   4.00       False  unknown  Southampton   yes       00대
889         1  male  26.00        True        C    Cherbourg   yes       20대

[93 rows x 8 columns]

In [ ]:
file_s_c['age_group'].unique()

array(['30대', '20대', '00대', '10대', '40대', '50대', '60대', '80대'],
      dtype=object)

In [ ]:
file_s_c['age_group'].mode()

0    20대
Name: age_group, dtype: object

In [ ]:
file_s_c['age_group'].value_counts()

age_group
20대    25
30대    23
00대    19
40대    12
10대     7
50대     4
60대     2
80대     1
Name: count, dtype: int64

In [ ]:
file_s_c_ag_2=file_s_c['age_group']=="20대"
file_s_c_ag_2

21     False
23      True
74     False
78     False
81      True
       ...
831    False
838    False
857    False
869    False
889     True
Name: age_group, Length: 93, dtype: bool

In [ ]:
file_s_c[file_s_c_ag_2]['embark_town'].mode()

0    Southampton
Name: embark_town, dtype: object

In [ ]:
file_s_c[file_s_c_ag_2]['deck'].value_counts()

deck
unknown    17
D           2
E           2
C           2
A           1
B           1
Name: count, dtype: int64

In [ ]:
file_s_c[file_s_c['age_group']=="30대"]['embark_town'].mode()

0    Southampton
Name: embark_town, dtype: object

In [ ]:
file_s_c[file_s_c['age_group']=="30대"]['deck'].value_counts()

deck
unknown    11
B           5
E           4
D           2
C           1
Name: count, dtype: int64




---



---






생존률이 여성보다 낮은 남성 중에서 생존률이 가장 높은 연령대는 20대이고

이 20대는 주로 Southampton에서 탑승하였다

또한 데크 번호는 결측치를 제외하고 주로 DEC를 사용했다는 사실을 알 수 있다.



---



추가적으로 생존자 남성 중 생존률이 가장 높은 연령대는 20대이지만

2명의 차이로 낮은 30대도 주로 Southampton에서 탑승하였다.

또한 데크 번호는 결측치를 제외하고 B를 주로 사용했다는 것이 밝혀졌다.